### ISSUE TITLE
FR7.  BFS

### ISSUE THREAD

**Issue by hishaam19** [WSU-4110/Algo-simulation#10]
|FR7.  BFS|
|---|
|**Goal:** The user will be able to select “BFS” and use our tool to simulate the step by step process of creating a BFS algorithm.
**Stakeholders:** User/Developers|
| **Description:** Breadth-first search is an algorithm for searching a tree data structure for a node that satisfies a given property. It starts at the tree root and explores all nodes at the present depth prior to moving on to the nodes at the next depth level. |
| **Origin**: The team came up with this during our first meeting, it is a requirement that each of our algorithms will have.|
| **Version** 1.0 |
| **Date:** 05/30/22 |
| **Priority:** 2|

**Comment by j-wallace-44** [comment]
This functional requirement has been implemented in the TreeSearches.html page
