### ISSUE TITLE
FR13. Tree traversal(Inorder)

### ISSUE THREAD

**Issue by hishaam19** [WSU-4110/Algo-simulation#19]
|FR13. Tree traversal(Inorder)|
|---|
|**Goal:** The user will be able to select “Tree traversal” and use our tool to simulate the step by step process of creating a Tree traversal algorithm.
**Stakeholders:** Users|
| **Description:** The objective of In-order Tree traversal is to start from the root and then traverse to the left subtree. After it traverses through the left tree, the in-order tree traversal goes through the right side and will spit out the answer in greatest to least. |
| **Origin**: The team came up with this during our first meeting, it is a requirement that each of our algorithms will have.|
| **Version** 1.0 |
| **Date:** 05/30/22 |
| **Priority:** 2|

**Comment by j-wallace-44** [comment]
This functional requirement has been implemented.
