### ISSUE TITLE
FR1. Description Logs

### ISSUE THREAD

**Issue by hishaam19** [WSU-4110/Algo-simulation#2]
|FR1. Description Logs|
|---|
|**Goal:** For each algorithm that is being simulated, a small description will be shown to explain the traversal of the algorithm.
**Stakeholders**: Users|
| **Description:** When each algorithm is being traversed, a small description (under the animation) of what is being done will be shown to help the user keep track of what is being done. |
| **Origin**: Team members decided to add description to each algorithm to help the user understand each algorithm, the team decided this was a FR in the first meeting. |
| **Version** 1.0 |
| **Date:** 05/30/22 |
| **Priority:** 1|

**Comment by j-wallace-44** [comment]
Description log feature is implemented for bubble sort algorithm.
