### ISSUE TITLE
FR2. User input to determine input of algorithms

### ISSUE THREAD

**Issue by hishaam19** [WSU-4110/Algo-simulation#4]
|FR2. User input to determine input of algorithms|
|---|
|**Goal:** The user will be able to input their own information into the algorithm (if applicable).
**Stakeholders:** Users|
| **Description:** The user will be able to input their own information into the algorithm to see how it works. There will be a size limit that is yet to be determined but it will be around 20-30 items (this may change) based on the specific algorithm. In general each algorithm will have a default input that is determined by the developers if the user chooses to not change the input. |
| **Origin**: The team came up with this during our first meeting, it is a requirement that each of our algorithms will have.|
| **Version** 1.0 |
| **Date:** 05/30/22 |
| **Priority:** 1|

**Comment by BharathPalanisamy** [comment]
User input is available now for bubble sort
