### ISSUE TITLE
FR3. Explanation/Pseudocode

### ISSUE THREAD

**Issue by hishaam19** [WSU-4110/Algo-simulation#5]
|FR3. Explanation/Pseudocode|
|---|
|**Goal:** Each algorithm we include will have a section with an explanation of the algorithm as well as pseudocode (if applicable).
**Stakeholders:** Users/Developers|
| **Description:** The explanation section will explain how the algorithm works as well as what it does and what it is used for. The pseudocode section will show the implementation of the code in popular formats such as c++.|
| **Origin**: This was discussed in our original requirements meeting which each algorithm will have. |
| **Version** 1.0 |
| **Date:** 05/30/22 |
| **Priority:** 1|

**Comment by j-wallace-44** [comment]
Pseudocode is available in bubble sort algorithm.

**Comment by j-wallace-44** [comment]
Pseudocode is available for the binary tree traversals page.
