### ISSUE TITLE
FR4. User interface

### ISSUE THREAD

**Issue by hishaam19** [WSU-4110/Algo-simulation#6]
|FR4. User interface|
|---|
|**Goal:** This will create the general interface that the user will use to access our website and switch from one algorithm to another.
**Stakeholders:** Users/Developers|
| **Description:** Since our team is doing a web based application we will need to create an interface for the user to use to access each different algorithm. |
| **Origin**: The team came up with this during our first meeting, it is a requirement that each of our algorithms will have.|
| **Version** 1.0 |
| **Date:** 05/30/22 |
| **Priority:** 1|

**Comment by joshpeete** [comment]
UI for the algorithms we've already completed is cohesive. UI template for future algorithms is available.
