### ISSUE TITLE
FR6. DFS

### ISSUE THREAD

**Issue by hishaam19** [WSU-4110/Algo-simulation#9]
|FR6. DFS|
|---|
|**Goal:** The user will be able to select “DFS” and use our tool to simulate the step by step process of creating a DFS algorithm. 
**Stakeholders:** Users/Developers|
| **Description:** Depth-first search is an algorithm for traversing or searching tree or graph data structures. The algorithm starts at the root node and explores as far as possible along each branch before backtracking. |
| **Origin**: Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version** 1.0 |
| **Date:** 05/30/22 |
| **Priority:** 2|

**Comment by j-wallace-44** [comment]
This functional requirement has been implemented in the treeSearches.html file.
